---
output: github_document
---

# Restored Marsh Biodiversity

## Summary

This is the code repository for the article, *Can created saltmarshes match biodiversity of pre-existing ones across scales? An assessment from microbes to predators*, published in *Ecosphere*.Scripts for reproducing the analyses and figures can be found below. 

<!-- Badges start -->

<!-- Badges end -->

## Reproducing the code

| Step                         |               Script                               |
| ---------------------------- | :------------------------------------------------: |
| clean data                   |    [:computer:](code/01_load-data.R)               |
| measurement of biodiversity  |    [:computer:](code/02_analyze-MoB.R)             |
| partition beta diversity     |    [:computer:](code/03_analyze-beta-partition.R)  |
| plot abundances              |    [:computer:](code/04_make-abundance-figures.R)  |
| plot diversities             |    [:computer:](code/05_make-diversity-figures.R)  |
| plot rarefactions            |    [:computer:](code/06_make-rarefaction-figures.R)|
| plot similarities            |    [:computer:](code/07_make-dendrogram-figures.R) |
| plot effects                 |    [:computer:](code/08_make-effects-figures.R)    |
| plot general effects         |    [:computer:](code/09_make-gen-effect-figures.R) |
| plot effects on S            |    [:computer:](code/10_make-effect-S-figures.R)   |
| plot SAD                     |    [:computer:](code/11_make-SAD-figures.R)        |

## Reproducibility

Version information for the when this repository was last updated can be found below.

<details><summary>Reproducibility receipt</summary>

```{r version info, warning=FALSE, message=FALSE}
## datetime
Sys.time()

source(here::here("code/01_load-data.R"))
## session info
sessionInfo()
```

</details>
